// Objective-C API for talking to scalecloud Go package.
//   gobind -lang=objc scalecloud
//
// File is generated by gobind. Do not edit.

#ifndef __ScaleCloudGo_H__
#define __ScaleCloudGo_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * GetLogs returns the last known node state token on the first line ("STATE:<token>"),
followed by all captured tsnet log lines. Clears the log buffer after read.
Swift splits on the first newline to get state and logs separately.
 */
FOUNDATION_EXPORT NSString* _Nonnull ScaleCloudGoGetLogs(void);

FOUNDATION_EXPORT BOOL ScaleCloudGoStartProxy(NSString* _Nullable hostname, NSString* _Nullable stateDir, long* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL ScaleCloudGoStopProxy(NSError* _Nullable* _Nullable error);

#endif
